export const RIDE_STATUS = [
  'REQUESTED',
  'DRIVER_ASSIGNED',
  'DRIVER_ARRIVING',
  'DRIVER_ARRIVED',
  'RIDE_STARTED',
  'RIDE_IN_PROGRESS',
  'RIDE_COMPLETED',
  'CANCELLED_BY_PASSENGER',
  'CANCELLED_BY_DRIVER',
  'CANCELLED_BY_SYSTEM',
  'SCHEDULED',
];

export const RIDE_BOOKED_FOR = ['ME', 'SOMEONE'];
